language: node_js
node_js:
- 8.11.1
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng build --prod --aot
after_success:
- rsync -e 'ssh -o StrictHostKeyChecking=no -i /tmp/deploy_rsa' -ravzup public/* $FTP_USER@$FPT_HOST:~/app/
before_install:
- openssl aes-256-cbc -K $encrypted_aa95179e8820_key -iv $encrypted_aa95179e8820_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- openssl aes-256-cbc -K $encrypted_43c5ea8c55b5_key -iv $encrypted_43c5ea8c55b5_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
